sudo: required
services: 
  - docker

before_install:
  - docker build -t abechraoui/dockerKubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true abechraoui/dockerKubernetes npm run test -- --coverage